#!/bin/bash
source /etc/profile
source ~/.bashrc

USERNAME=$(whoami)

#if [[ $EUID -ne 0 ]]; then
    echo ''
	echo -e "${COLOR_GREEN} ====Главное меню==== ${COLOR_NC}"

	echo '1: Управление сайтами'
	echo '2: Управление пользователями'
	echo '3: Управление базами данных'
	echo '4: Управление бэкапами'
	echo '5: Git'
	echo '9: Сервер'
	echo 'q: Выход'
	echo ''
	echo -n 'Выберите пункт меню:'
		
	while read
    do
        case "$REPLY" in
        "1")  $MENU/site.sh $USERNAME;  break;;
        "2")  $MENU/user.sh $USERNAME;  break;;
		"3")  $MENU/sql.sh $USERNAME;  break;;
		"4")  $MENU/backup.sh $USERNAME;  break;;
		"5")  $MENU/git.sh $USERNAME;  break;;
		"9")  $MENU/server.sh $USERNAME;  break;;
        "q"|"Q")  exit 0;; 
         *) echo -n "Команда не распознана: ('$REPLY'). Повторите ввод:" >&2;;
        esac
    done
